//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.SaleReports = new HashSet<SaleReport>();
        }
    
        public int GameID { get; set; }
        public string HomeClubName { get; set; }
        public string VisitorName { get; set; }
        public System.DateTime GameDate { get; set; }
        public int GameLocation { get; set; }
        public int GameStatus { get; set; }
    
        public virtual GameStatus GameStatus1 { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<SaleReport> SaleReports { get; set; }
    }
}
