//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Games = new HashSet<Game>();
            this.Terminals = new HashSet<Terminal>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int LocationID { get; set; }
        public string LocationName { get; set; }
        public bool LocationStatus { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
        public virtual ICollection<Terminal> Terminals { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
