//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesman
    {
        public int SalesmanID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int AssignedTerminal { get; set; }
        public bool Status { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Terminal Terminal { get; set; }
    }
}
