//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReportDetail
    {
        public int RowID { get; set; }
        public int ReportID { get; set; }
        public int TerminalID { get; set; }
        public int TicketID { get; set; }
        public int TicketQty { get; set; }
        public decimal TicketAmount { get; set; }
    
        public virtual SaleReport SaleReport { get; set; }
        public virtual Terminal Terminal { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
