//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TASEntities : DbContext
    {
        public TASEntities()
            : base("name=TASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameStatus> GameStatuses { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SaleReportDetail> SaleReportDetails { get; set; }
        public virtual DbSet<SaleReport> SaleReports { get; set; }
        public virtual DbSet<SaleReportStatus> SaleReportStatuses { get; set; }
        public virtual DbSet<Terminal> Terminals { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Salesman> Salesmen { get; set; }
    }
}
