//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal
    {
        public Terminal()
        {
            this.SaleReportDetails = new HashSet<SaleReportDetail>();
            this.Salesmen = new HashSet<Salesman>();
        }
    
        public int TerminalID { get; set; }
        public int LocationID { get; set; }
        public bool Status { get; set; }
        public string UUID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<SaleReportDetail> SaleReportDetails { get; set; }
        public virtual ICollection<Salesman> Salesmen { get; set; }
    }
}
