//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.SaleReportDetails = new HashSet<SaleReportDetail>();
        }
    
        public int TicketID { get; set; }
        public int TicketLocation { get; set; }
        public string Name { get; set; }
        public decimal Value { get; set; }
        public bool Status { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<SaleReportDetail> SaleReportDetails { get; set; }
    }
}
